"""Baseline: the schema as it stood when Alembic was introduced.

Autogenerated from app/models.py against an empty database, so it is
exactly what `create_all` used to build — every table, every column,
including the ones the old `_ADDED_COLUMNS` list in app/db.py used to
bolt on by hand after the fact.

A database that predates Alembic is never run through this revision. It
is stamped with it instead (see app/db.py::init_db), because its tables
already exist. That is also why the nullability here can differ slightly
from such a database: columns added by the old hand-patcher were created
nullable with a DEFAULT, whereas a table built fresh from this revision
gets them NOT NULL. The values are the same either way — the app has
always written them from Python — so the two are left to differ rather
than taking an ACCESS EXCLUSIVE lock on a live table to align a
constraint nothing depends on.

Revision ID: 0001_baseline
Revises: —
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('daily_messages',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('interests', sa.String(length=500), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_notified_date', sa.String(length=10), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('referral_bonus_quota', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('energy_refreshed_date', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('zodiac_sign', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('spread_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('spread_id', sa.String(length=64), nullable=False),
    sa.Column('spread_title', sa.String(length=255), nullable=False),
    sa.Column('cards_json', sa.String(), nullable=False),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('amount_rub', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_payments_yookassa_payment_id'), ['yookassa_payment_id'], unique=True)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quota_total', sa.Integer(), nullable=False),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('spread_follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spread_record_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=32), nullable=False),
    sa.Column('question_label', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spread_record_id'], ['spread_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spread_record_id', 'question_key')
    )


def downgrade() -> None:
    op.drop_table('spread_follow_ups')
    op.drop_table('subscriptions')
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_payments_yookassa_payment_id'))

    op.drop_table('subscription_payments')
    op.drop_table('spread_records')
    op.drop_table('users')
    op.drop_table('daily_messages')
